[project]
name = "starbit-va-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.8.0",
    "ddgs>=9.14.4",
    "nltk>=3.10.1",
    "ollama>=0.6.2",
    "openai>=2.47.0",
    "pipecat-ai[kokoro,local,silero,whisper]>=1.7.0",
    "python-dotenv>=1.2.2",
    "regex>=2026.7.19",
    "requests>=2.34.2",
    "sounddevice>=0.5.5",
]

[dependency-groups]
dev = [
    "ruff>=0.15.22",
]
